### ISSUE TITLE
Keep getting Game Error...

### ISSUE THREAD

**Issue by JourneyOver** [meepen/salien-bot#16]
Running tampermonkey, installed script and went to `https://steamcommunity.com/saliengame/play/`. Every time the page loads it throws the error `There was an error loading required game content. Your game will be restarted.` and if I click on `OK` page reloads and then throws the error once. This seems to be on a continuous loop as it always seems to throw the error everytime the page loads.

**Comment by ehea617** [comment]
This is an issue with Steam's servers and not with this userscript.

**Comment by JourneyOver** [comment]
Except for the fact that when I disable the script the game loads just fine. It's only happening when I have the script enabled.

**Comment by JourneyOver** [comment]
This is the error in the chrome dev console window
https://i.imgur.com/09ucZ2X.png

which seems to only happen when I have your script enabled, if I disable the script nothing ever pops up in the console window..

**Comment by Js41637** [comment]
Because the script is automatically trying to start the game, that error is because the games API returned an error. It has nothing to do with the script.

**Comment by JourneyOver** [comment]
Yep figured that out now, the script is broken for *monkey ways, have to manually click play and go to an world and open console and use it that way otherwise it'll just always throw the error and require page reload on a constant loop.

**Comment by Js41637** [comment]
It's probably because the script only works if the url has `/` at the end.

@meepen this line should probably be changed
https://github.com/meepen/salien-bot/blob/30eab5361b7c9fc01075afd28aa9c668eb713a12/index.user.js#L7

**Comment by JourneyOver** [comment]
Can confirm that doing the above works so I'd suggest making the change above @meepen

**Comment by Js41637** [comment]
I fixed this in a PR, make sure you update your script.

**Comment by bb10** [comment]
I still have this, even with v3. It just doesn't show the dialog anymore, it's just stuck in a loop refreshing the page.

**Comment by meepen** [comment]
for some reason the merge thought it was just another line added instead of changed?
fixing now

**Comment by JourneyOver** [comment]
@meepen the merge was correct, there was supposed to be a `// @match        https://steamcommunity.com/saliengame/play` and a `// @match        https://steamcommunity.com/saliengame/play/` both of them. There wasn't a removal at all just an addition.

**Comment by Js41637** [comment]
Sorry, I should have been a bit more clear in the pull request I made.

**Comment by dumpsters** [comment]
This happens to me both in firefox with violentmonkey and chromium with tampermonkey, the solution in https://github.com/meepen/salien-bot/issues/16#issuecomment-399268302 works, maybe adding it to the readme would be a good idea as a workaround.
